print('We are building the gpa calculator for you!')
print('========================================')
name=str(input('Enter your magical name::'))
print("Thanks,",name)
print("Now,let's calculate your beautiful GPA,")
print('As you are knowladgeble citizen,please make sure to enter your real gpa🥸')
a=float(input('Enter your GPA in the subject IIT::'))
b=float(input('Enter your GPA in the subject C Programming::'))
c=float(input('Enter your GPA in the subject Digital Logics::'))
d=float(input('Enter your GPA in the subject Mathematics I::'))
e=float(input('Enter your GPA in the subject Physics::'))
average=(a+b+c+d+e)
print('You have obtained,',average,'in total.')
credit=(average*3)
gpa=(credit/15)
print('Voila Your final GPA is:',gpa)
